FROM alpine:3.12

RUN \
    apk --no-cache add ca-certificates \
    autoconf \
    automake \
    build-base \
    glib \
    glib-dev \
    libc-dev \
    libtool \
    linux-headers \
    bison flex-dev unixodbc unixodbc-dev txt2man \
    unrar p7zip \
    git \
    && \
    echo "..."
RUN \
    mkdir -p "/opt/mdbdata" && \
    cd /tmp && \
    git clone https://github.com/mdbtools/mdbtools.git && \
    cd mdbtools && \
    echo "..."
RUN \
    autoreconf -i -f 
RUN \
    ./configure --with-unixodbc=/usr/local --mandir=/usr/share/man && make && make install 
RUN \
    cp README "/opt/mdbdata/" 
RUN \
    cd /tmp && rm -r mdbtools 
RUN \
    apk del autoconf automake build-base glib-dev libc-dev unixodbc-dev flex-dev git 
RUN \
    echo "In order to work interactively, mount a volume to /opt/mdbdata before starting this docker container." >> "/opt/mdbdata/README" && \
    echo "Example: docker run -it --rm -v /path/to/host/directory:/opt/mdbdata rillke/mdbtools-docker bash" >> "/opt/mdbdata/README"

COPY scripts/* /usr/bin

# set pager used by `man` to less
ENV PAGER="less"

WORKDIR "/opt/mdbdata"

