name: build-deb
on:
  push:
    branches:
      - master
env:
  TAG_VERSION: ${{formatDate("YYMMDD-HHmmss", new Date())}}
  DH_ID_base: kitaruk/mdbtools-docker

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set Image Tag
        run: |
          if [ -n "$(git tag)" ]; then
            export IMAGE_TAG="$(git tag)"
          else
            export IMAGE_TAG="${{env.TAG_VERSION}}"
          fi

      - name: Build and push Docker image
        run: |

          docker build \
                  --pull \
                  --platform linux/amd64 \
                  -f Dockerfile.build-deb-src \
                  -t "${{env.DH_ID_base}}:build-deb" \
                  -t "${{env.DH_ID_base}}:build-deb-${{env.TAG_VERSION}}" \
                  .
      - name: Login to GitHub Container Registry
        run: docker login docker.pkg.github.com -u ${{secrets.GITHUB_USERNAME}} -p ${{secrets.GITHUB_TOKEN}}


      - name: Push Docker Image
        run: |
          docker push \
            docker.pkg.github.com/${{secrets.GITHUB_USERNAME}}/${{env.DH_ID_base}}:${{env.TAG_VERSION}}